### PR TITLE
Ligatures

### PR DESCRIPTION
**Pull request by sabberworm**
Support the [ligatures setting](https://github.com/nfroidure/svgicons2svgfont/pull/27) of svgicons2svgfont. I thought using an event to customize glyph settings was a neat idea but feel free to change this.

### CODE REVIEW

**Comment by elexx** [comment]
:+1: for this pull request!

**Comment by nfroidure** [comment]
@elexx would you add some tests for it?

**Comment by sabberworm** [comment]
@elexx @nfroidure: https://github.com/fontello/svg2ttf/pull/32 is still not merged so there are no releases of svg2ttf with ligature support. As soon as there are, I will try adding tests to both svgicons2svgfont and this project.

**Comment by puzrin** [comment]
@sabberworm sorry for delay. I've closed ALL pending tails. That includes big `svgpath` rewrite for arcs support and other improvments.

The only thing to do before release is check [lsb patch](https://github.com/fontello/svg2ttf/tree/lsb), wich should fix wrong horizontal adjustment. See details in https://github.com/fontello/svg2ttf/issues/29

It would be nice if someone experienced could take a look.

**Comment by nfroidure** [comment]
Closing since the feature is now covered per the 2.0.0 version. Thanks to everyone!

**Pull request closed without merging**
