### PR TITLE
Use different unicode PUA to avoid conflicts with iOS emoticons and VoiceOver

### PR DESCRIPTION
**Pull request by backflip**
VoiceOver on iOS reads 0xE001 as "boy's head" since it is used for a corresponding emoticon (see screenshot below). [This article](http://www.filamentgroup.com/lab/bulletproof_icon_fonts.html) by @zachleat has further details. Judging from http://www.fileformat.info/info/unicode/block/private_use_area/utf8test.htm, starting at 0xEA01 would be safe (for now). Tested on iOS 8.

@zachleat, do you know of any downsides of using 0xEA01 and above?

screen-shot-2015-05-26-at-15 52 58

### CODE REVIEW

**Comment by zachleat** [comment]
You can check http://unicode.johnholtripley.co.uk/ which has some great compatibility tables for screen readers! cc @johnholtripley

I’m not sure any unicode glyph is truly safe cross browser, which is why we encourage `aria-hidden=true`, as stated in the article.

**Comment by nfroidure** [comment]
Will merge for the 2.0 version since it includes breaking changes. Thx for the PR.

**Comment by backflip** [comment]
Thanks @zachleat! I have linked your blog post in the README with the notion of `additional suggestions regarding accessibility`. @nfroidure, is that okay with you?

**Comment by nfroidure** [comment]
Of course it is ;).

**Pull request merged**
